"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Variable para la vista del clima
OPENWEATHER_API_KEY = os.getenv('OPENWEATHER_API_KEY')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_728x00&_v-a!=ewo5ow=dv(fb8_!esx5q5@+l=zn)%pg5s+)*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '2061-2804-6fc-c06c-a000-94e6-619c-612a-9ce.ngrok-free.app',
    '.ngrok.io',  
]

CSRF_TRUSTED_ORIGINS = [
    'https://2061-2804-6fc-c06c-a000-94e6-619c-612a-9ce.ngrok-free.app',
    'https://*.ngrok.io', 
]

# Application definition
INSTALLED_APPS = [
    # 1. CLOUDINARY_STORAGE DEBE IR PRIMERO SÍ O SÍ
    'cloudinary_storage',       
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # 2. STATICFILES DEBE IR DESPUÉS DE CLOUDINARY_STORAGE
    'django.contrib.staticfiles',
    
    'comunidad',
    
    # 3. LA APP DE CLOUDINARY
    'cloudinary',               
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], 
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',    
                'django.template.context_processors.request',  
                'django.contrib.auth.context_processors.auth', 
                'django.contrib.messages.context_processors.messages', 
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es' # Cambiado a español para CLIMA-PROYECTO
TIME_ZONE = 'America/Sao_Paulo' # Zona horaria local
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# ==========================================
# CONFIGURACIÓN DE MEDIA Y CLOUDINARY
# ==========================================

# 4. CREDENCIALES (Busca en el .env, si no encuentra, usa las hardcodeadas)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', "dv2rf4agm"),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', "226996355489362"),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', "7ueqWkzASzRG-KXWL_e0kaUK2_Y")
}

# 5. FORZAR ALMACENAMIENTO EN LA NUBE
# AGREGAR ESTO:
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# 6. RUTAS BÁSICAS DE MEDIA (Django las pide aunque usemos Cloudinary)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')